### ISSUE TITLE
Keep it simlpe

### ISSUE THREAD

**Issue by Goutte** [JaccomoLorenz/godot-simlpe-screenshot-script#1]
… and keep it fersh ! Thank you for this script, `yield(get_tree(), "idle_frame")` is pretty clever :bowing_man:

**Comment by Maujoe** [comment]
"Simple" mainly should mean that it's can be used by plug and play if "Keep it simple" was intended to be a request.

`Thank you for this script, yield(get_tree(), "idle_frame") is pretty clever 🙇`
Thanks,  it's actually from the Screen Capture example: [https://godotengine.org/asset-library/asset/130](url).

**Comment by Goutte** [comment]
I just like "simlpe" as a keyword, for some reason. :smile: 

---

I made [a plugin using screenshots in a automated way to build spritesheets](https://github.com/Goutte/godot-spritesheet-generator) !
